matrix:
  include:
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode7.3

install:
  - brew uninstall --force brew-cask
  - brew update
  - brew cask install flash-player

script:
  - echo ok
